function Re = importRe(filename)
%IMPORTFILE Import data from a text file
%  LMCHANNEL0180MEANPROF = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  LMCHANNEL0180MEANPROF = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  LMChannel0180meanprof = importfile("/home/lloydfung/MATLAB-Drive/PoissonChannelTest/Data/LM_Channel_0180_mean_prof.dat", [43, 43]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Jun-2024 13:51:30

%% Input handling


    dataLines = [43, 43];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "=";

% Specify column names and types
opts.VariableNames = ["Var1", "VarName2"];
opts.SelectedVariableNames = "VarName2";
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
Re = readtable(filename, opts);

%% Convert to output type
Re = table2array(Re);
end